# 使用前请安装Bio和CAI库
# pip install Bio
# pip install CAI
# 导入第三方库
from Bio import SeqIO
from CAI import RSCU
# 读取序列
seqs = [record.seq for record in SeqIO.parse('example.fasta','fasta')]
# 打印属性
i = 1
for seq in seqs:
    print("序列"+str(i)+":")
    print(seq)
    i = i+1
# 计算RSCU值
rscu = RSCU(seqs,5)
print("RSCU:")
print(rscu)
# 密码子表，1标准
# c2aa = {
#         'TGT':'Cys',
#         'UGU':'Cys',
#         'TGC':'Cys',
#         'UGC':'Cys',
#         'GAT':'Asp',
#         'GAU':'Asp',
#         'GAC':'Asp',
#         'GAC':'Asp',
#         'TCT':'Ser',
#         'UCU':'Ser',
#         'TCG':'Ser',
#         'UCG':'Ser',
#         'TCA':'Ser',
#         'UCA':'Ser',
#         'TCC':'Ser',
#         'UCC':'Ser',
#         'AGC':'Ser',
#         'AGC':'Ser',
#         'AGT':'Ser',
#         'AGU':'Ser',
#         'CAA':'Gln',
#         'CAA':'Gln',
#         'CAG':'Gln',
#         'CAG':'Gln',
#         'ATG':'Met',
#         'AUG':'Met',
#         'AAC':'Asn',
#         'AAC':'Asn',
#         'AAT':'Asn',
#         'AAU':'Asn',
#         'CCT':'Pro',
#         'CCU':'Pro',
#         'CCG':'Pro',
#         'CCG':'Pro',
#         'CCA':'Pro',
#         'CCA':'Pro',
#         'CCC':'Pro',
#         'CCC':'Pro',
#         'AAG':'Lys',
#         'AAG':'Lys',
#         'AAA':'Lys',
#         'AAA':'Lys',
#         'ACC':'Thr',
#         'ACC':'Thr',
#         'ACA':'Thr',
#         'ACA':'Thr',
#         'ACG':'Thr',
#         'ACG':'Thr',
#         'ACT':'Thr',
#         'ACU':'Thr',
#         'TTT':'Phe',
#         'UUU':'Phe',
#         'TTC':'Phe',
#         'UUC':'Phe',
#         'GCA':'Ala',
#         'GCA':'Ala',
#         'GCC':'Ala',
#         'GCC':'Ala',
#         'GCG':'Ala',
#         'GCG':'Ala',
#         'GCT':'Ala',
#         'GCU':'Ala',
#         'GGT':'Gly',
#         'GGU':'Gly',
#         'GGG':'Gly',
#         'GGG':'Gly',
#         'GGA':'Gly',
#         'GGA':'Gly',
#         'GGC':'Gly',
#         'GGC':'Gly',
#         'ATC':'Ile',
#         'AUC':'Ile',
#         'ATA':'Ile',
#         'AUA':'Ile',
#         'ATT':'Ile',
#         'AUU':'Ile',
#         'TTA':'Leu',
#         'UUA':'Leu',
#         'TTG':'Leu',
#         'UUG':'Leu',
#         'CTC':'Leu',
#         'CUC':'Leu',
#         'CTT':'Leu',
#         'CUU':'Leu',
#         'CTG':'Leu',
#         'CUG':'Leu',
#         'CTA':'Leu',
#         'CUA':'Leu',
#         'CAT':'HIS',
#         'CAU':'HIS',
#         'CAC':'HIS',
#         'CAC':'HIS',
#         'CGA':'Arg',
#         'CGA':'Arg',
#         'CGC':'Arg',
#         'CGC':'Arg',
#         'CGG':'Arg',
#         'CGG':'Arg',
#         'CGT':'Arg',
#         'CGU':'Arg',
#         'AGG':'Arg',
#         'AGG':'Arg',
#         'AGA':'Arg',
#         'AGA':'Arg',
#         'TGG':'Trp',
#         'UGG':'Trp',
#         'GTA':'Val',
#         'GUA':'Val',
#         'GTC':'Val',
#         'GUC':'Val',
#         'GTG':'Val',
#         'GUG':'Val',
#         'GTT':'Val',
#         'GUU':'Val',
#         'GAG':'Glu',
#         'GAG':'Glu',
#         'GAA':'Glu',
#         'GAA':'Glu',
#         'TAT':'Tyr',
#         'UAU':'Tyr',
#         'TAC':'Tyr',
#         'UAC':'Tyr',
#     }
# 遗传密码表，5无脊椎动物
c2aa = {
    "GCA":"Ala",
    "GCC":"Ala",
    "GCG":"Ala",
    "GCT":"Ala",
    "CGA":"Arg",
    "CGC":"Arg",
    "CGG":"Arg",
    "CGT":"Arg",
    "AAC":"Asn",
    "AAT":"Asn",
    "GAC":"Asp",
    "GAT":"Asp",
    "TGC":"Cys",
    "TGT":"Cys",
    "CAA":"Gln",
    "CAG":"Gln",
    "GAA":"Glu",
    "GAG":"Glu",
    "GGA":"Gly",
    "GGC":"Gly",
    "GGG":"Gly",
    "GGT":"Gly",
    "CAC":"His",
    "CAT":"His",
    "ATC":"Ile",
    "ATT":"Ile",
    "CTA":"Leu1",
    "CTC":"Leu1",
    "CTG":"Leu1",
    "CTT":"Leu1",
    "TTA":"Leu2",
    "TTG":"Leu2",
    "AAA":"Lys",
    "AAG":"Lys",
    "ATA":"Met",
    "ATG":"Met",
    "TTC":"Phe",
    "TTT":"Phe",
    "CCA":"Pro",
    "CCC":"Pro",
    "CCG":"Pro",
    "CCT":"Pro",
    "AGA":"Ser1",
    "AGC":"Ser1",
    "AGG":"Ser1",
    "AGT":"Ser1",
    "TCA":"Ser2",
    "TCC":"Ser2",
    "TCG":"Ser2",
    "TCT":"Ser2",
    "TAA":"Ter",
    "TAG":"Ter",
    "ACA":"Thr",
    "ACC":"Thr",
    "ACG":"Thr",
    "ACT":"Thr",
    "TGA":"Trp",
    "TGG":"Trp",
    "TAC":"Tyr",
    "TAT":"Tyr",
    "GTA":"Val",
    "GTC":"Val",
    "GTG":"Val",
    "GTT":"Val",
}
fw = open('rscu.txt','w')
# 临时的氨基酸字典，用于计算第4列
amino_acid = {}
# 判断是否重复，每重复一次，第4列的值减0.5
count = 0
for codon, value in rscu.items():
    count = count +1
    # print("密码子:%s" % codon)
    # print("RSCU值:%s" % value)
    if c2aa[codon] not in amino_acid:
        amino_acid[c2aa[codon]] = 6
    else:
        amino_acid[c2aa[codon]] -= 0.5
    print(codon + "," + c2aa[codon] + "," + str(round(value, 3)) + "," + str(amino_acid[c2aa[codon]]))
    fw.write(codon + "," + c2aa[codon] + "," + str(round(value, 3)) + "," + str(amino_acid[c2aa[codon]]) + "\n")
print("密码子："+str(count))
fw.close()
